version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: snout-postgres
    environment:
      POSTGRES_DB: snout
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
