/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package snout.notes.api;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;



@SpringBootApplication
public class App {
    private static final Logger log = LoggerFactory.getLogger(App.class);

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        log.info("Servidor iniciou");
        SpringApplication.run(App.class, args);
    }
}
